black:
  max:
  - 115
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 175
  - 94
  min:
  - 0
  - 0
  - 0
green:
  max:
  - 255
  - 110
  - 255
  min:
  - 47
  - 0
  - 135
red:
  max:
  - 135
  - 190
  - 175
  min:
  - 0
  - 149
  - 154
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
yellow:
  max:
  - 255
  - 141
  - 255
  min:
  - 0
  - 0
  - 140
